version: '3.8'

services:

  mongodb: 
    image: mongo:latest
    hostname: localhost
    env_file: .env  
    volumes:   
      - ./mongodb/scripts/:/docker-entrypoint-initdb.d/ 
      - ./mongodb/dump:/data/dump  
      - /data/mongodb/project_crud/data:/data/db 
    restart: always 
    networks:  
        - db_network

  web:  
    build: 
      context: .
      dockerfile: ./Dockerfile 
    ports:
      - "3001:3001"
    env_file: .env
    environment:
      - PORT=3001
    restart: always 
    depends_on:
      - mongodb
    networks:  
        - db_network

networks:  
  db_network:
